array_width                 = 95
comment_width               = 120
edition                     = "2021"
format_code_in_doc_comments = true
imports_granularity         = "Crate"
max_width                   = 120
reorder_imports             = true
use_small_heuristics        = "Max"
